services:
  bff:
    image: web-bff:v1
    build:
      context: .
    ports:
      - 8081:8080
    networks:
      - hireben-network
    depends_on:
      - redis
    environment:
      APP_SERVER_PORT: 8080
      DEMO_SERVICE_ENVIRONMENT: dev
      DEMO_SERVICE_REST_WEB_BFF_ID: REST_WEB_BFF
      DEMO_SERVICE_REST_WEB_BFF_SECRET_KEY: hireBenDemoSecretKey
      DEMO_DATABASE_REDIS_HOST: redis
      DEMO_DATABASE_REDIS_PORT: 6379
      DEMO_DATABASE_REDIS_USERNAME: bff
      DEMO_DATABASE_REDIS_PASSWORD: demo
      APP_SESSION_TTL: 1800
      APP_USER_SESSION_TTL: 3600
      APP_MAX_ACTIVE_USER_SESSIONS: 3
      APP_SESSION_CLEAN_UP_INTERVAL: 60000

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - hireben-network
    volumes:
      - ./redis.conf:/etc/redis/redis.conf:ro
    command: ["redis-server", "/etc/redis/redis.conf"]
      
networks:
  hireben-network:
    external: true